name: Consolerizer Main Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build and Test
      run:  mvn clean install jacoco:prepare-agent package jacoco:report

    - name: Coverage Reports
      run: mvn omni-coveragereporter:report
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    - name: Build and Test Spring Boot Tester
      run:  make build-maven-spring-boot

    - name: Maven OWASP Security Check
      run: mvn clean install -Powasp
