name: Consolerizer PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: make b

      - name: Coverage
        run: make coverage

      - name: Build and Test Spring Boot Tester
        run:  make build-maven-spring-boot
